apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  tls:
    - hosts:
        - www.wonend.cn
      secretName: ssl-wonend
  rules:
    - host: www.wonend.cn
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: startpage-service
              port:
                number: 80